name: Build and Push Docker Image to GHCR

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Docker image tag (e.g., latest, v1.0.0)'
        required: true
        default: 'latest'
      image_path:
        description: 'Path for the Docker image (e.g., urlshortner, myapp)'
        required: true
        default: 'urlshortner'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker Image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/${{ github.event.inputs.image_path }}:${{ github.event.inputs.image_tag }} .

      - name: Push Docker Image to GHCR
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/${{ github.event.inputs.image_path }}:${{ github.event.inputs.image_tag }}
